# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuppressionFournisseurConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 200)
        Dialog.setMinimumSize(QtCore.QSize(420, 200))
        Dialog.setMaximumSize(QtCore.QSize(420, 200))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(85, 27))
        self.label_2.setMaximumSize(QtCore.QSize(8888888, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(85, 27))
        self.label_3.setMaximumSize(QtCore.QSize(8888888, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(85, 27))
        self.label_4.setMaximumSize(QtCore.QSize(85, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.chercher_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.chercher_lineEdit.setMinimumSize(QtCore.QSize(220, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chercher_lineEdit.setFont(font)
        self.chercher_lineEdit.setObjectName("chercher_lineEdit")
        self.horizontalLayout.addWidget(self.chercher_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.annuler_pushButton = QtWidgets.QPushButton(Dialog)
        self.annuler_pushButton.setMinimumSize(QtCore.QSize(70, 27))
        self.annuler_pushButton.setObjectName("annuler_pushButton")
        self.horizontalLayout_2.addWidget(self.annuler_pushButton)
        self.supprimer_pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.supprimer_pushButton_2.setMinimumSize(QtCore.QSize(70, 27))
        self.supprimer_pushButton_2.setObjectName("supprimer_pushButton_2")
        self.horizontalLayout_2.addWidget(self.supprimer_pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.annuler_pushButton.clicked.connect(Dialog.close) # type: ignore
        self.supprimer_pushButton_2.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Etes vous sure de vouloir supprimer le fournisseur séléctionner ?"))
        self.label_3.setText(_translate("Dialog", "Veuillez entrer le bon resultats pour confirmer la suppression ( 4+7 )"))
        self.label_4.setText(_translate("Dialog", "Résultat"))
        self.annuler_pushButton.setText(_translate("Dialog", "Annuler"))
        self.supprimer_pushButton_2.setText(_translate("Dialog", "Supprimer"))
