# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 183)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFile_2 = QtWidgets.QMenu(self.menubar)
        self.menuFile_2.setObjectName("menuFile_2")
        MainWindow.setMenuBar(self.menubar)
        self.actionFournisseur = QtWidgets.QAction(MainWindow)
        self.actionFournisseur.setObjectName("actionFournisseur")
        self.actionPole = QtWidgets.QAction(MainWindow)
        self.actionPole.setObjectName("actionPole")
        self.actionItem = QtWidgets.QAction(MainWindow)
        self.actionItem.setObjectName("actionItem")
        self.actionDivision = QtWidgets.QAction(MainWindow)
        self.actionDivision.setObjectName("actionDivision")
        self.actionProjet = QtWidgets.QAction(MainWindow)
        self.actionProjet.setObjectName("actionProjet")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionFournisseur)
        self.menuFile.addAction(self.actionItem)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDivision)
        self.menuFile.addAction(self.actionPole)
        self.menuFile.addAction(self.actionProjet)
        self.menuFile.addSeparator()
        self.menuFile_2.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ERP"))
        self.menuFile.setTitle(_translate("MainWindow", "Table de base"))
        self.menuFile_2.setTitle(_translate("MainWindow", "File"))
        self.actionFournisseur.setText(_translate("MainWindow", "Fournisseur"))
        self.actionPole.setText(_translate("MainWindow", "Pole"))
        self.actionItem.setText(_translate("MainWindow", "Item"))
        self.actionDivision.setText(_translate("MainWindow", "Division"))
        self.actionProjet.setText(_translate("MainWindow", "Projet"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
