# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 602)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(240, 0))
        self.widget.setMaximumSize(QtCore.QSize(240, 16777215))
        self.widget.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    background-color:transparent;\n"
"    border-bottom:1px solid #d1d1d1;\n"
"\n"
"    color: #666;\n"
"    letter-spacing:1.0px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgba(255,255,255,1);\n"
"    outline:none;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    /*color: #d9d9d9;*/\n"
"};\n"
"\n"
"/*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 63, 140, 174), stop:1 rgba(0, 27, 74, 183));*/\n"
"\n"
"    background-color: rgb(244, 246, 249);\n"
"    border-right:2px solid #d9d9d9;\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 8, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashBoard_pushButton = QtWidgets.QPushButton(self.widget)
        self.dashBoard_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dashBoard_pushButton.setFont(font)
        self.dashBoard_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashBoard_pushButton.setStyleSheet("")
        self.dashBoard_pushButton.setObjectName("dashBoard_pushButton")
        self.verticalLayout.addWidget(self.dashBoard_pushButton)
        self.fournisseur_pushButton = QtWidgets.QPushButton(self.widget)
        self.fournisseur_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fournisseur_pushButton.setFont(font)
        self.fournisseur_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fournisseur_pushButton.setStyleSheet("")
        self.fournisseur_pushButton.setObjectName("fournisseur_pushButton")
        self.verticalLayout.addWidget(self.fournisseur_pushButton)
        self.item_pushButton = QtWidgets.QPushButton(self.widget)
        self.item_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.item_pushButton.setFont(font)
        self.item_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.item_pushButton.setStyleSheet("")
        self.item_pushButton.setObjectName("item_pushButton")
        self.verticalLayout.addWidget(self.item_pushButton)
        self.pole_pushButton = QtWidgets.QPushButton(self.widget)
        self.pole_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pole_pushButton.setFont(font)
        self.pole_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pole_pushButton.setStyleSheet("")
        self.pole_pushButton.setObjectName("pole_pushButton")
        self.verticalLayout.addWidget(self.pole_pushButton)
        self.nt_pushButton = QtWidgets.QPushButton(self.widget)
        self.nt_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nt_pushButton.setFont(font)
        self.nt_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nt_pushButton.setStyleSheet("")
        self.nt_pushButton.setObjectName("nt_pushButton")
        self.verticalLayout.addWidget(self.nt_pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 324, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 6, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
"color: #303844;\n"
"border: none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 4, 1, 1, 1)
        self.deconnexion_pushButton = QtWidgets.QPushButton(self.widget)
        self.deconnexion_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deconnexion_pushButton.setFont(font)
        self.deconnexion_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deconnexion_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deconnexion_pushButton.setStyleSheet("")
        self.deconnexion_pushButton.setObjectName("deconnexion_pushButton")
        self.gridLayout_2.addWidget(self.deconnexion_pushButton, 7, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 6, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setMinimumSize(QtCore.QSize(600, 600))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dashBoard_pushButton.setText(_translate("MainWindow", "DashBoard"))
        self.fournisseur_pushButton.setText(_translate("MainWindow", "Fournisseur"))
        self.item_pushButton.setText(_translate("MainWindow", "Item"))
        self.pole_pushButton.setText(_translate("MainWindow", "Pole"))
        self.nt_pushButton.setText(_translate("MainWindow", "NT"))
        self.label.setText(_translate("MainWindow", "Cosider canalisation"))
        self.deconnexion_pushButton.setText(_translate("MainWindow", "Déconnexion"))
